apiVersion: v1
items:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: "2020-05-31T19:09:24Z"
    labels:
      app: ace
    name: ace
    namespace: exceptions
    resourceVersion: "455111114"
    selfLink: /apis/build.openshift.io/v1/namespaces/exceptions/buildconfigs/ace
    uid: 3deb65a4-a372-11ea-9655-0a580a8100f0
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: ace:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: nodejs
      git:
        uri: https://github.com/carlossagala/workshops.git
      sourceSecret:
        name: git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: nodejs:10
          namespace: openshift
      type: Source
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: u26E0eHd4PTUjVA4bS-7
      type: GitHub
    - generic:
        secret: TPKuUdODtHKaLwF85x-N
      type: Generic
    - type: ConfigChange
    - imageChange:
        lastTriggeredImageID: image-registry.openshift-image-registry.svc:5000/openshift/nodejs@sha256:bce9d648821108fb7046b33b6f3f1b49607fd44a242de2a6a0a538f56e353153
      type: ImageChange
  status:
    lastVersion: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
